sonar.projectKey=testing-nest
sonar.host.url=http://localhost:9000/
sonar.token=sqp_2ce961908791ea3bef7e0798e3a5da7240a58ab6
sonar.sources=src
sonar.tests=test
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.e2e-spec.ts,\
  **/main.ts,\
sonar.test.inclusions=\
  **/*.spec.ts,\
  **/*.e2e-spec.ts
sonar.coverage.exclusions=\
  **/*.spec.ts,\
  **/*.e2e-spec.ts,\
  **/main.ts,\
  **/*.module.ts,\
  **/migrations/**,\
  **/config/**
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=\
  **/*.spec.ts,\
  **/migrations/**
sonar.testExecutionReportPaths=./test-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info